Repository architectury/architectury-loom, pull requests merged in 2021-12, with the labels that each got.

#59 Add architectury decompiler
  src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
  src/main/java/net/fabricmc/loom/api/decompilers/architectury/ArchitecturyLoomDecompiler.java
  src/main/java/net/fabricmc/loom/configuration/providers/MinecraftProviderImpl.java
  src/main/java/net/fabricmc/loom/configuration/providers/forge/McpConfigProvider.java
  src/main/java/net/fabricmc/loom/configuration/providers/forge/MinecraftPatchedProvider.java
  src/main/java/net/fabricmc/loom/extension/LoomGradleExtensionApiImpl.java
  src/main/java/net/fabricmc/loom/extension/MinecraftGradleExtension.java
  src/main/java/net/fabricmc/loom/task/ArchitecturyGenerateSourcesTask.java
  src/main/java/net/fabricmc/loom/task/GenerateSourcesTask.java
  src/main/java/net/fabricmc/loom/task/LoomTasks.java
  src/main/java/net/fabricmc/loom/util/srg/SpecialSourceExecutor.java
Labels: enhancement, new feature, api, priority: medium

#61 Allow transitive access wideners to be declared through architectury.…
  src/main/java/net/fabricmc/loom/configuration/accesswidener/AccessWidenerFile.java
  src/main/java/net/fabricmc/loom/task/RemapJarTask.java
Labels: new feature, api, priority: high

#64 Add forgeRuntimeLibrary configuration + some clean up
  src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java
  src/main/java/net/fabricmc/loom/configuration/providers/forge/ForgeUserdevProvider.java
  src/main/java/net/fabricmc/loom/util/Constants.java
  src/main/java/net/fabricmc/loom/util/DependencyDownloader.java
Labels: enhancement
