Repository architectury/architectury-loom, pull requests merged in 2023-08, with the labels that each got.

#154 Support Neo
  src/main/java/net/fabricmc/loom/configuration/providers/forge/ForgeLibrariesProvider.java
Labels: priority: low, small change, Forge

#145 Add a mod settings container to RunConfigSettings
  src/main/java/net/fabricmc/loom/configuration/ide/RunConfigSettings.java
  src/main/java/net/fabricmc/loom/configuration/providers/forge/ForgeRunsProvider.java
  src/main/java/net/fabricmc/loom/task/launch/GenerateDLIConfigTask.java
  src/test/groovy/net/fabricmc/loom/test/integration/forge/ForgeRunConfigTest.groovy
Labels: enhancement, priority: low

#153 feat: make forge don't care mod manifest
  src/main/java/net/fabricmc/loom/build/nesting/JarNester.java
  src/main/java/net/fabricmc/loom/util/fmj/FabricModJsonFactory.java
Labels: bug, Forge
